### PR TITLE
refactor: removed some unused parameter warnings.

### PR DESCRIPTION
**Pull request by lukester1975**
As subject.

Happy to change them for `[[maybe_unused]]` if you prefer...

### CODE REVIEW

**Comment by codeinred** [comment]
Hi! Thank you so much for fixing this! It seems like google benchmark changed the way you're supposed to declare the main function, which is why all the tests were failing. I added a commit fixing that, and if all the tests are successful I'll merge it!

**Comment by lukester1975** [comment]
No problem, thanks for taking a look.

Have you considered using the benchmark facilities in catch2 and reducing deps? Been a while since I've compared them, so don't know what might be missing but I've been happy with it for my own stuff!

**Comment by codeinred** [comment]
I have considered it, although google benchmark is only a dependency of the library if you're building everything (benchmarks and tests included). If you're only installing tuplet or using it as a dependency with cmake_FetchContent, google benchmark shouldn't be downloaded! (Please let me know if it is, this would be a bug)

I like the way google benchmark does benchmarks, which is why I've continued using it

**Comment by codeinred** [comment]
I integrated the fix mentioned in #21, as the problems mentioned in that issue were still causing tests to fail. Let me know if there are any further issues with MSVC, please!

**Pull request merged**
